# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-09 18:36
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Departure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.DateTimeField(max_length=50)),
                ('arrival_time', models.DateTimeField(max_length=50)),
                ('pilot1', models.CharField(max_length=50, null=True)),
                ('pilot2', models.CharField(max_length=50, null=True)),
                ('board', models.IntegerField()),
                ('place1', models.BooleanField(default=False)),
                ('place2', models.BooleanField(default=False)),
                ('place3', models.BooleanField(default=False)),
                ('place4', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'departure',
                'verbose_name_plural': 'departures',
            },
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('latitude', models.FloatField(max_length=20)),
                ('longitude', models.FloatField(max_length=20)),
                ('info', models.TextField(null=True)),
                ('to', django.contrib.gis.db.models.fields.PointField(blank=True, srid=4326)),
            ],
            options={
                'verbose_name': 'destination',
                'verbose_name_plural': 'destinations',
            },
        ),
        migrations.CreateModel(
            name='Helipad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(max_length=20)),
                ('longitude', models.FloatField(max_length=20)),
                ('title', models.CharField(max_length=50)),
                ('departure_location', models.CharField(max_length=50)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, srid=4326)),
            ],
            options={
                'verbose_name': 'helipad',
                'verbose_name_plural': 'helipads',
            },
        ),
        migrations.CreateModel(
            name='HelipadOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=50)),
                ('contact_name', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_point', models.CharField(max_length=50)),
                ('destination_point', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'route',
                'verbose_name_plural': 'routes',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastname', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='destination',
            name='helipad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helipads.Helipad'),
        ),
        migrations.AddField(
            model_name='departure',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helipads.Route'),
        ),
    ]
