# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-12 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helipads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Helicopter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
    ]
