# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-13 12:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helipads', '0004_auto_20160512_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='departure',
            name='helicopter',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='helipads.Helicopter'),
            preserve_default=False,
        ),
    ]
