# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-13 12:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helipads', '0005_departure_helicopter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departure',
            name='helicopter',
        ),
    ]
