# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-13 13:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helipads', '0007_helicopter_route'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='helicopter',
            name='route',
        ),
        migrations.AddField(
            model_name='departure',
            name='helicopter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='helipads.Helicopter'),
            preserve_default=False,
        ),
    ]
