# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-16 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helipads', '0008_auto_20160513_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='departure',
            name='ticket_cost',
            field=models.IntegerField(default=35),
            preserve_default=False,
        ),
    ]
