# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-24 18:37
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helipads', '0011_auto_20160523_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='destination_location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, srid=4326),
        ),
        migrations.AddField(
            model_name='route',
            name='starting_location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, srid=4326),
        ),
    ]
