# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-26 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helipads', '0013_auto_20160525_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helicopter',
            name='image',
            field=models.ImageField(upload_to='helicopter'),
        ),
    ]
