# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-26 16:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helipads', '0016_auto_20160526_1502'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_id', models.IntegerField()),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.CharField(blank=True, max_length=50)),
                ('departure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helipads.Departure')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helipads.RegularUser')),
            ],
            options={
                'verbose_name': 'ticket',
                'verbose_name_plural': 'tickets',
            },
        ),
    ]
