# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-30 16:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helipads', '0017_ticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_seat', models.IntegerField()),
                ('departure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helipads.Departure')),
                ('ticket', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='helipads.Ticket')),
            ],
        ),
    ]
