# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-30 16:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helipads', '0018_seat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seat',
            options={'verbose_name': 'seat', 'verbose_name_plural': 'seats'},
        ),
        migrations.AlterField(
            model_name='seat',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='helipads.Ticket'),
        ),
    ]
