# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-02 16:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helipads', '0020_auto_20160601_1846'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='seat_id',
            new_name='seat_number',
        ),
    ]
