# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-03 14:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helipads', '0021_auto_20160602_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='place',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='helipads.Seat'),
            preserve_default=False,
        ),
    ]
