# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-06 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helipads', '0022_ticket_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='seat_number',
            field=models.IntegerField(null=True),
        ),
    ]
