# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-07 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helipads', '0023_auto_20160606_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='regularuser',
            name='firstname',
            field=models.CharField(default='Ivan', max_length=50),
            preserve_default=False,
        ),
    ]
