# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-13 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helipads', '0024_regularuser_firstname'),
    ]

    operations = [
        migrations.AddField(
            model_name='helipadowner',
            name='organization',
            field=models.CharField(default='Organization', max_length=70),
            preserve_default=False,
        ),
    ]
